### ISSUE TITLE
rebooting host, lose screen after bios screen

### ISSUE THREAD

**Issue by danmed** [mtlynch/tinypilot#104]
tiny pilot shows just a black screen.. no amount of rebooting the pi seems to bring it back.

**Comment by danmed** [comment]
a second reboot of the host brought it back.. maybe it was just a quirk.

**Comment by somik123** [comment]
@danmed  I had the same issue. It was a issue with the PC as connecting my portable hdmi monitor (before reboot) 'also showed black screen. Not sure if caused by the cheapo hdmi to usb device or not...
