### ISSUE TITLE
Are there any html files in the sytem i can customise?

### ISSUE THREAD

**Issue by danmed** [mtlynch/tinypilot#105]
I'd like to work on a theme for TinyPilot but i can't find the html files. are there any or are they all baked in ?

**Comment by mtlynch** [comment]
Sure, the HTML file is here:

https://github.com/mtlynch/tinypilot/blob/master/app/templates/index.html

The CSS is here:

https://github.com/mtlynch/tinypilot/blob/master/app/static/css/style.css
