### ISSUE TITLE
Is the init-usb-gadget script specific to Raspberry Pi 4 ?

### ISSUE THREAD

**Issue by lamarios** [mtlynch/tinypilot#135]
I managed to setup tinypilot on my [upsquared](https://up-board.org/upsquared/specifications/) board that has a USB OTG port and the keyboard is the only thing I can't get to work so my question to know if the init-usb-gadget script is specific to the RPi4 ? That's the only script of the project that I don't understand at all...

When I run it I do have the /dev/hidg0  device but I can't get it to work with tiny pilot.  

When I press keys on tinypilot U the key strokes appear in green in the history but nothing on the screen (I verified with physical keyboard and the video signal works).

Thanks for that amazing project.

**Comment by mtlynch** [comment]
Thanks for testing it out.

The OTG support currently works only on Pi 4 and Pi Zero W. There's more work we have to do to get compatibility working on other SBCs. We're tracking support for alternate hardware here:

https://github.com/mtlynch/tinypilot/issues/79
