### ISSUE TITLE
Error running quick_install to update

### ISSUE THREAD

**Issue by danmed** [mtlynch/tinypilot#137]
I'm receiving this error when running quick_install to update the version : 

Command "/tmp/tmp.g8xVFkS0KG/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7ajrzbrn/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-cvqkxub2/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/tmp.g8xVFkS0KG/venv/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-install-7ajrzbrn/cffi/

This is on a pi4 using the recommended distro.

**Comment by mtlynch** [comment]
Thanks for reporting this! You're seeing this repeatedly?

Could you share a [gist](https://gist.github.com/) of the full output?

**Comment by danmed** [comment]
Yeah i'm seeing it repeatedly even after a reboot..

gimme a few mins and i'll post a gist

**Comment by mtlynch** [comment]
Hmm, not sure why it's suddenly failing without this package. This should fix it:

```bash
sudo apt-get install -y libffi-dev
```
