### ISSUE TITLE
Feature Request: USB-A to USB-A support

### ISSUE THREAD

**Issue by mengesb** [mtlynch/tinypilot#154]
Greetings,

In playing with your project a little, I wanted to explore using a USB-A to USB-A cable (3.0 or 2.0) between RPi and client system. Normally all my RPis run PoE, therefore USB-C for Power+KB-HID device actually results in a little bit of noise/feedback (TinyPilot RPi to RPi). Theoretically if this could be supported, that'd lead way to supporting more than one KVM interface per RPi (You've got quite the thread on #81 so I'll leave that discussion there).

My main interest is dropping the need for USB-C, and replacing that with USB-A on the TinyPilot RPi.

Also - I have a number of RPi3b's that spec was are fairly similar to RPi4 low end models... if we can instead use a USB-A 2.0 port instead of the RPI4's USB-C port, then I could also put my RPI3bs to use as KVMs too ... is there enough CPU power to run this? My RPi3bs are also controlled mostly by PoE, but I have a few that are MicroUSB powered with a dedicated 6-power port supply for the stack.

**Comment by mtlynch** [comment]
Thanks for checking out the project!

>I wanted to explore using a USB-A to USB-A cable (3.0 or 2.0) between RPi and client system.

Unfortunately, this is not possible. On the Pi 4, only the USB-C port has OTG support, so that's the only port capable of impersonating a USB device on the target system. The Pi 3 has no USB ports that support OTG, so it's not possible to run TinyPilot on the Pi 3.
