### ISSUE TITLE
Capture card models wiki page

### ISSUE THREAD

**Issue by rvdwegen** [mtlynch/tinypilot#187]
It looks like the factories in China are pumping out a good amount of different ~$10 USB capture cards. It might be a nice idea to create a wiki page documenting the different models.
I think it would be interesting to see if there are any quality/hardware/functionality differences.

So far I've found about 9 different looking models in the ~$10 range.

**Comment by rvdwegen** [comment]
Small update, I've ordered 6 or 7 models.

**Comment by mtlynch** [comment]
Good idea. Added!

https://github.com/mtlynch/tinypilot/wiki/HDMI-Capture-Devices
