### ISSUE TITLE
Troubleshooting guide

### ISSUE THREAD

**Issue by nickodell** [mtlynch/tinypilot#222]
Do you have any kind of troubleshooting guide? I'm currently trying to debug a latency problem, (intermittent latency of about 4 seconds) and I can't figure out where to start.

I'd be willing to contribute to it - I've already found several areas where setup is non-obvious. (Networking and using non-data USB cables.)

**Comment by UEA-envsoft** [comment]
Maybe the Wiki?

**Comment by mtlynch** [comment]
Thanks for the suggestion! I've added a page to the wiki for this:

https://github.com/mtlynch/tinypilot/wiki/Troubleshooting-and-Diagnostics

Let me know if you're still running into issues.
