### ISSUE TITLE
Data USB / keyboard not working

### ISSUE THREAD

**Issue by alex-phillips** [mtlynch/tinypilot#286]
## Description

When I plug in the 'data' USB into the computer, the terminal outputs the following and no input is detected:

![image](https://user-images.githubusercontent.com/3135216/95605986-b3b64000-0a27-11eb-9e58-9bd6a6a5bc24.png)

## What's the behavior that you expect?

USB to allow keyboard input

## What's happening instead?

See screenshot above.

## What are the steps to reproduce this behavior?

1. Plug data USB into machine (linux, ubuntu 20.04 specifically)

## Logs

Please paste the URL you see when you run `/opt/tinypilot/dev-scripts/dump-logs`

http://sprunge.us/ILKTaM

**NOTE**: I am using a spliced USB cable following the diagram below. This is due to the splitter being backordered and other options taking a month or longer to ship.

![image](https://user-images.githubusercontent.com/3135216/95606202-ff68e980-0a27-11eb-919d-704a569c8868.png)

**Comment by djclueless** [comment]
When you spliced the cables, did you use common ground

The usb host and the power supply ground cables need be spliced together.

**Comment by alex-phillips** [comment]
Yesh - from the Pi is red (power), green (data +), white (data -), and black (ground). I spliced from the power supply, red and black to the USB cable and to the host, I spliced white, green, and black.

I will say that the USB C cable I used didn't have a 'black' ground but it appears its ground was unshielded and loose so assumed this was the ground whereas the cable from the power supply specifically has a black wire (this was not a USB-C cable but a USB-A cable I just needed for the PSU end).

**Comment by alex-phillips** [comment]
@djclueless so all three connections are sharing a twisted black or unshielded wire. All other wires are only shared by 2 of the 3 ends.

**Comment by djclueless** [comment]
Do you have an unmodified USB-C cable to test?

Just connect the PI to the computer using a regular cable.  See if the keyboard works? This would be the easiest way to figure out if its a cable issue.

I spliced my own cable as well, so yours should look similiar to the picture below (I know it's messy but it works). Basically what you explained.

From Power supply you have:
- Positive (red to USB-C)
- Negative (black or shield or white in my case to both the USB-A and USB-C).

From USB-C (PI) you have:
- Positive (red from p/s)
- Negative (black or shield from p/s & negative to USB-A host)
- Data cable + (White or Green to usb-a host)
- Data cable - (White or Green to usb-a host)

From USB-A (Host) you have:
- Negative (Black or shield to USB-C and p/s)
- Data cable + (White or Green to USB-A)
- Data cable - (White or Green to USB-A)
- No Positive (Red cable should be cut and not connected to anything)



![image](https://user-images.githubusercontent.com/22175951/95608689-7fdd1980-0a2b-11eb-8ba8-7c75ef60706b.png)

**Comment by alex-phillips** [comment]
@djclueless Thanks for the info! I've attached screenshots of my three cable splices. Mine's a lot messier, but wanted to get it working before I cleaned it up. One thing I noticed is that the USB-A cable that is connected to the  power supply has both a black and an unshielded wire, which I currently don't have connected to anything. Any idea what that would be if it also has a specific black wire?

PSU Wire:
![image](https://user-images.githubusercontent.com/3135216/95610336-2aeed280-0a2e-11eb-9dcb-1295e2dc0b97.png)


Pi Wire:
![image](https://user-images.githubusercontent.com/3135216/95610355-32ae7700-0a2e-11eb-8705-47b08522ab34.png)

Host wire:
![image](https://user-images.githubusercontent.com/3135216/95610366-380bc180-0a2e-11eb-9a62-978b15ad073f.png)

**Comment by mtlynch** [comment]
>This is due to the splitter being backordered and other options taking a month or longer to ship.

Just to clarify, everything is currently in stock. You saw things listed as out of stock on [this page](https://tinypilotkvm.com/products)?

Did the USB-C cable work before you spliced it? There are some that just don't work with USB OTG for whatever reason, including Amazon Basics brand ones.

**Comment by alex-phillips** [comment]
@mtlynch When I checked in September it said it was backordered. Glad to see everything's back in stock!

@djclueless  But it does look like it's a cable issue. I tried with an unmodified USB-C cable (same brand and type) and it doesn't seem to be working. I'll test it out with another and report back.

Thank you both for helping troubleshoot!

**Comment by alex-phillips** [comment]
@mtlynch is there a specific brand you'd recommend getting? It seems none of the USB-C cables I have are working.

**Comment by mtlynch** [comment]
@alex-phillips - For a regular USB-C to USB-A connection between the Pi and the target computer, I know [Anker](https://smile.amazon.com/gp/product/B07DD5YHMH/) works reliably. I've never tried any DIY splicing with it though.

If you want to skip the DIY splicing, I recommend:

* [TinyPilot power connector](https://tinypilotkvm.com/product/tinypilot-power-connector)
* [CableCreation 6" USB-C to USB-A](https://smile.amazon.com/gp/product/B012V56D2A/)
* [Rankie 3' MicroUSB to USB-A](https://smile.amazon.com/gp/product/B01JPDTZXK/) (it's a 3-pack, because you need two of these)

**Comment by alex-phillips** [comment]
@mtlynch Interesting. Both the cables I've tried are Anker (skipping the splicing).

**Comment by alex-phillips** [comment]
Let me try another server just in case there's something unusual about this motherboard...

**Comment by conrad784** [comment]
I found your issue, because I had the same error message. For my Supermicro board it worked by using the USB2.0 ports instead of 3.0.

**Comment by mtlynch** [comment]
@alex-phillips - Are you still seeing this behavior or did new cables resolve this?

**Comment by mtlynch** [comment]
Closing for now, but feel free to reopen if this is still an active issue.
