### ISSUE TITLE
Bootable removable storage emulation

### ISSUE THREAD

**Issue by WormChickenWizard** [mtlynch/tinypilot#289]
Ever since I discovered the tiny pilot project, I have been very intrigued by how it operates. It could really appeal to system builders/general computer technicians since it could save time and space not having to hook up another keyboard, mouse, and monitor in order to service another system. One thing that could be really useful in my opinion is to be able to upload an iso to the pi and have it emulate a flash drive that the computer being monitored could boot from. That could be very useful and could save time.

**Comment by mtlynch** [comment]
Thanks for checking out the project and the suggestion! I'm merging this with #75, which is I think the same feature request.
