### ISSUE TITLE
Replace manual modifier buttons with on-screen keyboard

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#302]
To allow the user to send key combinations that the OS or browser would otherwise trap (e.g., Ctrl+Alt+Del, Ctrl+T), we use manual modifier buttons below the remote screen:

![image](https://user-images.githubusercontent.com/7783288/96476786-aeb17780-1203-11eb-962f-15c4f1c4c76c.png)

These buttons aren't especially intuitive. 

### Desired Replacement

![image](https://user-images.githubusercontent.com/7783288/98825191-330da980-2402-11eb-9d47-6b8ff47f53f1.png)

### Behavior

* Modifier buttons (shift, control, super, alt)
  * Single click sends the keystroke immediately, but also puts them into "pressed" state.
  * If the user clicks a modifier key in "pressed" state, it reverts to non-pressed state and sends no keystroke.
  * If the user clicks a non-modifier key, TinyPilot should send all modifiers keys in "pressed" state as modifiers and then revert them to non-pressed state.
* Regular buttons
  * Single click sends the keystroke immediately.

* Keys should darken slightly when the user hovers over them.
* Keys should be in a darker state briefly when the user clicks them.
* Keys should visually represent when they're in "pressed" state.

### Implementation

* The key layout should be entirely HTML and CSS. You should use JavaScript to handle clicks but not to control layout.
* The implementation must not pull in any third-party libraries.
* The keyboard should be encapsulated in one or more [HTML custom elements](https://css-tricks.com/creating-a-custom-element-from-scratch/) (see examples of existing HTML custom elements in [`app/templates/custom-elements`](https://github.com/mtlynch/tinypilot/tree/master/app/templates/custom-elements)).
  * The custom element will replace the existing modifier keys [here](https://github.com/mtlynch/tinypilot/blob/da0ab48c9135a27c1df3c943e53f25bded8cde85/app/templates/components/keyboard-panel.html#L3L37)
* The keyboard custom element should communicate with the parent page (app.js) via JavaScript events.
  * [Simple event example](https://github.com/mtlynch/tinypilot/blob/da0ab48c9135a27c1df3c943e53f25bded8cde85/app/templates/custom-elements/key-history.html#L78)
  * [Advanced event example](https://github.com/mtlynch/tinypilot/blob/da0ab48c9135a27c1df3c943e53f25bded8cde85/app/templates/custom-elements/remote-screen.html#L298L310)
* Responsive design is not necessary
  * It's sufficient for the keyboard to render properly on viewports 800px or wider.

### Bounty

**A contributor is currently working on this.**

~~The contributor who submits a PR that fixes this issue will receive **$200** payable via PayPal. US residents may also receive payment via a mailed check if they prefer.~~

~~To prevent wasted effort from multiple people working simultaneously, you may comment on this issue to announce that you're working on the bounty. You'll get assigned the issue for 48 hours, during which no other submissions will be considered. Please only do this if you're actively working on the issue and expect to have a PR ready within 48 hours.~~

**Comment by manuschillerdev** [comment]
I was playing around with something very similar recently.
Just leaving this here in case it may help someone as starting point to implement your feature.

https://codesandbox.io/s/modest-breeze-3vl59?file=/src/index.js

**Comment by matt-curtis** [comment]
Was going to give this a shot, looks like someone's already working on it. If it opens back up let me know!
