### ISSUE TITLE
Add support for VNC / RDP

### ISSUE THREAD

**Issue by brentcetinich** [mtlynch/tinypilot#306]
In full screen mode it would be great if the Windows key and the Esc key were captured, even if this means some kind of thick client

**Comment by mtlynch** [comment]
@brentcetinich - Thanks for filing this! I'm planning to eventually add a VNC or RDP interface to TinyPilot, but it's going to be a significant undertaking.

**Comment by mtlynch** [comment]
Related: https://github.com/mtlynch/tinypilot/issues/522

**Comment by mtlynch** [comment]
Closing, tracking in separate bugs now:

* VNC: #107 
* Capture Escape key: #522
