### ISSUE TITLE
Ubuntu Server 20.04.01 LTS - Simple Install Fails

### ISSUE THREAD

**Issue by jharmon96** [mtlynch/tinypilot#316]
## Description

Simple Install Fails on Raspberry Pi 4 - 8GB running Ubuntu Server 20.04.01 LTS

**Error message:**
TASK [mtlynch.tinypilot : install TinyPilot pre-requisite packages] ************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'python-pip' is available"}

## What's the behavior that you expect?

Install to complete

## What's happening instead?

Install fails. 
Port 80 returns Nginx 502 Bad Gateway

## What are the steps to reproduce this behavior?

Build SD image with Raspberry Pi Installer

## Screenshots

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/48194176/98400992-f83af880-2032-11eb-962f-2af3e25f4ac4.png)

## Logs

Please paste the URL you see when you run `/opt/tinypilot/dev-scripts/dump-logs`

N/A

**Comment by jharmon96** [comment]
Just noticed Ubuntu isn't supported per the requirements. You can change this to a Feature Request.

**Comment by mtlynch** [comment]
Thanks for reporting this! Yeah, Ubuntu is unfortunately not supported at the moment.

#287 tracks the feature request to support Ubuntu.

**Comment by mtlynch** [comment]
Update: this is working now, as of this change:

https://github.com/mtlynch/ansible-role-tinypilot/pull/77
