### ISSUE TITLE
VirtualMedia

### ISSUE THREAD

**Issue by ITJamie** [mtlynch/tinypilot#342]
A lot of newer KVM solutions offer "virtual media" as a feature. It would be epic if we could do this on tinypilot.
Aka the ability to point to an ISO file or IMG file to mount a virtual cd-rom or virtual usb device for booting from etc

**Comment by mtlynch** [comment]
Thanks for filing this!

Unfortunately, I won't be able to offer this in the community edition of TinyPilot, as it's one of the premium features in [TinyPilot Pro](https://tinypilotkvm.com/pro).
