### ISSUE TITLE
Sending custom keycodes (e.g. Power) from TinyPilot?

### ISSUE THREAD

**Issue by victorhooi** [mtlynch/tinypilot#359]
I'm looking into whether we can use TinyPilot to remotely control some ChromeOS based devices.

These devices often have specific keys for things like "Search", or "Power".

I can get the keycodes for these - e.g. 0x98 is power.

However, is there any way to send custom keycodes to a device from TinyPilot?

And do you know if sending these will still work when the device is powered off?

**Comment by mtlynch** [comment]
Thanks for filing this!

That might be possible. I suspect that it won't work when the device is powered off, though.

Can you share screenshots of what appears when you push those keys while viewing [keycode.info](https://keycode.info/)?

**Comment by mtlynch** [comment]
Didn't hear back, so I'm closing, but feel free to reopen if you'd like to share screenshots.
