### ISSUE TITLE
Add support for OS Key doubleclick

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#37]
The way the modifier keys currently work is:

1. User pushes a modifier key button in the web UI
1. User presses a button on their physical keyboard

This causes TinyPilot to send the next key event with the modifier forced on (e.g., "Ctrl+T"), when it otherwise be captured by the browser.

![image](https://user-images.githubusercontent.com/7783288/94743377-46c6ea00-0345-11eb-9017-70577293ca1d.png)

It would be good to support a mechanism where the user can send *just* the modifier key. We should listen to the modifier keys `dblclick` events and send a key event of just the modifier key when that happens.

**Comment by somik123** [comment]
> Sometimes the OS key is useful to press by itself regardless of key combinations. Allow double click to just force a modifier key event on its own.

Some VM hosts monitor right cotnrol key as a modifier. If pressed, any key pressed after will be sent directly. Others like noVNC gives you a list of keys to press:

![Screenshot at 2020-07-24 19-49-22](https://user-images.githubusercontent.com/7911288/88388352-e9636980-cde6-11ea-8945-767e2f8b975d.png)

**Comment by somik123** [comment]
@mtlynch most key combinations other then predefined hotkeys works fine. In my case, Alt+V brings up my clipboard manager and it is not passed to browser, thus not to tinypilot. Similarly, unable to send Win key (like you said on your first post).
