### ISSUE TITLE
Does TinyPilot support Apple machines?

### ISSUE THREAD

**Issue by champignoom** [mtlynch/tinypilot#372]
It is said in the [PiKVM tutorial](https://github.com/pikvm/pikvm#Limitations) that there's a problem with Apple UEFI which requires a workaround with Arduino.

> To use Pi-KVM with Apple UEFI, use the Arduino HID even with v2. Apple UEFI wants the most blunt keyboard possible.

Does TinyPilot Also face this problem or does it somehow get over it?

Either way, it would be nice to have a sheet in the README showing testing status for popular devices.

Thanks.

**Comment by y0hnn** [comment]
yes it works

**Comment by champignoom** [comment]
Thanks

**Comment by mtlynch** [comment]
TinyPilot and PiKVM use the same video capture library, so if Apple UEFI doesn't work on PiKVM, it unfortunately won't work on TinyPilot.
