### ISSUE TITLE
Change device hostname through web UI

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#433]
As more users are deploying multiple TinyPilots to the same network, we should make it easier to change their hostnames.

Which changes the hostname to the desired

### Ansible

Add a script called `/opt/tinypilot-privileged/change-hostname` that the `tinypilot` user can execute as sudo to change the hostname in `/etc/hosts` and `/etc/hostname`.

The script can be written in bash or as a standalone Python script. See [this PR](https://github.com/mtlynch/ansible-role-tinypilot/pull/80) as an example of adding a privileged script.

Updating `/etc/hostname` is simple because it's a file with just the hostname, but `/etc/hosts` requires some care. We should ensure that:

* ~~We perform exactly one string replacement~~ (see update, below)
* ~~The string is in the position we expect~~ (see update, below)
* The hostname contains only [valid characters](https://man7.org/linux/man-pages/man7/hostname.7.html#:~:text=Valid%20characters%20for%20hostnames%20are,to%20an%20address%20for%20use.)
* The new hostname is not `localhost`

* **Update**: Per discussion, rather than updating the existing `/etc/hosts` entry, `change-hostname` should add a block to the top of /etc/hosts like this:

```bash
# AUTOGENERATED BY TINYPILOT <<<
127.0.1.1 my-custom-hostname.local
# >>> AUTOGENERATED BY TINYPILOT
```

The OS processes `/etc/hosts` from top to bottom, so our block will take precedence over future blocks.

### Backend

Add a new REST endpoint:

#### `/api/hostname` (PUT)

The API should accept a JSON message like this:

```javascript
{
  "hostname": "some-new-name"
}
```

The handler should call a module that wraps the call to `/opt/tinypilot-privileged/change-hostname` script using `subprocess`. See [`debug_logs.py`](https://github.com/mtlynch/tinypilot/blob/271d8dc54d8511ec1a738dd46523884e863d90b7/app/debug_logs.py) for a similar example.

The endpoint should respond with a message like this:

```javascript
{
  "success": true,
  "error": null
}
```

#### `/api/hostname` (GET)

Retrieves the current hostname like this:

```javascript
{
  "success": true,
  "error": null,
  "hostname": "tinypilot"
}
```

It should retrieve the hostname by ~~executing the system's `hostname` command and piping through the result~~ calling `platform.node`.

### Frontend

We should add an option under "Commands" that's "Change Hostname". It pops up a dialog box that says "Change hostname" and offers a text input showing the current hostname (from `/api/hostname`) and allows the user to change it.

**Added (2021-02-15)**: The dialog should include a warning at the bottom that says, "Your device will restart to apply this change."

~~If the user changes it, the dialog should say: "Restart now to apply changes?"~~

~~If the user chooses to reboot,~~ The dialog should call `/api/shutdown` to reboot and then poll in the background for a response at the new hostname URL. When the new URL is serving, the dialog should redirect the browser to the new URL.

**Comment by jotaen** [comment]
@mtlynch on a general note, do you have something in mind for how to go about the local dev server? Because right now it’s not mandatory to start the dev server in an environment where the priviledged scripts are available under `/opts/...`, so using these settings via the UI locally will produce errors. Along with the “shutdown” commands this is an additional case where the [dev and prod environments are not at par](https://12factor.net/dev-prod-parity).

**Comment by mtlynch** [comment]
>on a general note, do you have something in mind for how to go about the local dev server?

I don't have a good plan for that yet. It started out with the shutdown as the only privileged command, but then I've been slowly adding new ones over the past month and so there's more and more drift.

One thing we could do is define a configuration for an Ansible installation you can run in a dev environment so that it's closer to the prod setup and has the right scripts in place.

**Comment by jotaen** [comment]
How about mocking the scripts? (Or was that what you meant?) It’s not exactly parity, on the other hand there is little point in, e.g., changing the network config such as the host name, or shutting down the machine, when it’s all running locally. For me it would already be a good first step if the frontend didn’t crash in an odd way.

**Comment by mtlynch** [comment]
I was thinking of putting the real scripts in, but we could mock as well. I started a separate bug in #501 to track.

**Comment by jotaen** [comment]
I believe this is done, isn’t it? 🥳

**Comment by mtlynch** [comment]
Oh right. Fixed!

**Comment by AphinityAvali** [comment]
Multiple devices I've tried on the public fork of tinypilot will not accept anything entered in the hostname field, giving a warning of what characters are permitted each time.

**Comment by db39** [comment]
Hi @AphinityAvali, I'm sorry you ran into this error when setting a hostname using `.local` as a suffix. 

>it does appear to infer .local after reboot, so this is more of a UI confirmation that you do not need the .local

That's correct - you don't need to specify, `.local` here. I can see how it can be confusing to have the error appearing to say the format is invalid when you want to use `.local`.

![Image](https://github.com/user-attachments/assets/47477d67-1607-4651-9f3e-6cb01f9b56a1)

I've created a [new GitHub issue](https://github.com/tiny-pilot/tinypilot/issues/1879) to edit the error message to mention not needing `.local` (or similar). Please let me know if you have any questions or suggestions on this.
