### ISSUE TITLE
Solved: RPi Zero W no web interface and ustreamer ERROR on some devices

### ISSUE THREAD

**Issue by terxw** [mtlynch/tinypilot#438]
## Solution

the problems were on my side:

1. firefox auto redirect to https, I was aware of that but even in chrome the web was not working 
after I reinstalled with tinypilot_interface 0.0.0.0 e.g. 

` export TINYPILOT_INSTALL_VARS="ustreamer_capture_device=tc358743 tinypilot_interface=0.0.0.0"
`
then it worked!

2. on my server I tried passthrough my nvidia card (GT 1080) and I also blacklisted driver and let vfio manage also my host card ( GeForce GT 710B), after correcting that, all is fine.
3. 

## Description

I have two problems:

1. cannot connect to the web interface
2. cannot get ustreamer working on my proxmox server

Hardware:

rpi zero w Lusya HDMI to CSI-2 Adapter Board

software:

raspberry os lite

install tinypilotkvm with:

`
export TINYPILOT_INSTALL_VARS="ustreamer_capture_device=tc358743"
`

`
curl  --silent  --show-error  https://raw.githubusercontent.com/mtlynch/tinypilot/master/quick-install |  bash - && sudo reboot
`

## What's the behavior that you expect?

web interface accesible

stream working on my server

## What's happening instead?

1. web browser is unable to connect on port 80
 - although from logs I can see that there are no erros, ping, ssh works

2. If I connect to my laptop (through usb to hdmi adapter) I can see from logs that streaming is working e.g. there is data from hdmi
3. When i connect to my server hdmi, there is no output
 - possible reasons:  my server do not recognize tinypilot and thus no output

## Logs
logs connected to my server:
http://sprunge.us/psoRPp

logs connected to my laptop (changes tinypilot_interface to 0.0.0.0):

http://sprunge.us/3zLEeT

**Comment by mtlynch** [comment]
Glad to hear you got this figured out!

**Comment by mtlynch** [comment]
Also, `tinypilot_interface` is for the the backend. Nginx listens to 0.0.0.0 on port 80 and forwards the requests to the TinyPilot backend at localhost:8000.

There generally isn't a reason to have the TinyPilot backend also listen on 0.0.0.0.
