### ISSUE TITLE
Change uStreamer settings from the web UI

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#448]
I need to think through the implementation more, but it would be very helpful if users could adjust uStreamer settings directly from the web UI.

Currently, they have to edit their `/lib/systemd/system/ustreamer.service` file by hand, reload, and restart, which is cumbersome.

We should offer simple ways to adjust resolution, frame rate, and video quality.

## Loose design

1. Frontend offers overlay dialog to update uStreamer's FPS, ~~resolution~~, and JPEG quality.
2. When backend receives new settings, writes them to `/home/tinypilot/settings.yml` (we can backport [this module](https://github.com/tiny-pilot/tinypilot-pro/blob/923f18601192ae4d93855b7cce648dcc371cf482/app/update_settings.py) from TinyPilot Pro)
3. Run the [uStreamer update script](https://github.com/mtlynch/ansible-role-tinypilot/issues/110) to apply the settings

**Comment by mtlynch** [comment]
Let's hold off on adding resolution settings to the UI. I've been playing around with it on the Voyager, and I can't get uStreamer to accept any other resolution than the default, so it'll be a confusing user experience if they try changing the resolution and nothing happens.

Changing JPEG quality is still useful, though.

**Comment by jdeanwallace** [comment]
Okay cool. I know you're testing on the Voyager, but I didn't have any problems changing the uStreamer resolution using the HDMI-to-USB dongle. [Video demo](https://www.loom.com/share/37ea82ea0a814cc993da4349497392d7).

**Comment by mtlynch** [comment]
Yeah, it's successful for me on the USB dongle as well, but I can't figure out how to get it to change on the Voyager. I'm not sure if the TC358743 chip just doesn't support it and uStreamer won't resize down or if I'm just missing something.
