### ISSUE TITLE
The dev check scripts should disregard non-version-controlled files

### ISSUE THREAD

**Issue by jotaen** [mtlynch/tinypilot#502]
I use PyCharm, which generates an `.idea` folder. That folder is in my global `.gitignore` so it will never be commited. Regardless, `./dev-scripts/check-trailing-newline` checks it and complains, which causes the local build to be aborted. This can be worked around by adding `./idea/*` to that script – this is a bit inconvenient, however, and it also imposes the risk that such temporary and local modifications make it into the repo by accident (e.g. via a PR).

(Enhancement is technically not the right label, it’s not a bug either though.)

**Comment by mtlynch** [comment]
Oh, that's a good idea. As a short-term fix, can you submit a PR that adds `.idea` to the `check-trailing-newline` exceptions?

It seems like the more robust fix is to base the whitespace checks on `git ls-files` instead of excluding specific folders.
