### ISSUE TITLE
Servo for Power button presses?

### ISSUE THREAD

**Issue by SpeedGP** [mtlynch/tinypilot#519]
Silly idea, but how difficult would it be to implement a servo or solenoid that actually presses the power button if the machine is fully off?

We just had a ton of power outages in my area that the thought crossed my mind.

Thanks!!

**Comment by mtlynch** [comment]
That was one of the solutions I considered, but it's a bit too unreliable.

The direction I'm currently pursuing is to have TinyPilot control a power strip that can cut power to the machine if it becomes unresponsive. You'll have to configure your BIOS to always power on LAN, though.

Expect to see this in the next 2-3 months.
