### ISSUE TITLE
Create a generic HTML Custom Element for overlay dialogs

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#536]
We have a lot of overlay dialogs repeating the same code. We should create a generic dialog that can eliminate some of the repetition.

**Comment by jotaen** [comment]
The generic overlay component should not just bundle the styling, but it also should take care of functional things like preventing keypresses from getting send to the remote machine while it is open.

**Comment by mtlynch** [comment]
Fixed in #585
