### ISSUE TITLE
Disable caching of static assets

### ISSUE THREAD

**Issue by jotaen** [mtlynch/tinypilot#565]
Someone (flask? nginx?) seems to be setting cache headers for the static assets. Is that deliberate?

I think the benefit of caching is probably not super huge, but the downside is that it can result in weird intermediate states after having performed an update of tinypilot. E.g. it gives you a new `index.html` but `style.css` is still an old one.

I have also been running into this quite often during development.

<img width="363" alt="Screenshot 2021-03-10 at 19 02 08" src="https://user-images.githubusercontent.com/3618384/110675531-47588c00-81d3-11eb-9068-a4cf6a52e026.png">

**Comment by mtlynch** [comment]
Yeah, on the real device, nginx [turns caching off](https://github.com/mtlynch/ansible-role-tinypilot/blob/93c73d43028aa6c1bf26319813b66aa9a121a8f3/tasks/nginx.yml#L51L59). If you're talking directly to Flask, then we use Flask's defaults which I guess enable caching.

This seems like a reasonable solution:

https://stackoverflow.com/a/50173687/90388
