### ISSUE TITLE
Add hostname to title

### ISSUE THREAD

**Issue by DAVe3283** [mtlynch/tinypilot#577]
It would be useful to have the hostname in the title for a couple reasons:

1. Easily identify the correct TinyPilot tab when you have multiple
2. Enable password managers (e.g. KeePass) to identify the correct entry for auto-type.

I propose instead of naming the tab `TinyPilot`, it could be `HostName - TinyPilot`. So if you had set the TinyPilot's hostname to `Server01-KVM` the tab title would be `Server01-KVM - TinyPilot`.

**Comment by mtlynch** [comment]
Good idea! Fixed in #581.
