### ISSUE TITLE
Cannot get keyboard presses to be recognized 

### ISSUE THREAD

**Issue by cdgriffith** [mtlynch/tinypilot#602]
## Description

I have a tinypilot Raspberry PI 4 connected to a TrueNAS SCALE (Debian 10 base) that does not recognize keyboard input at anypoint (bios / grub / OS). 

I have tried setting `MOUSE_PATH` to /dev/null as well as changing `/opt/tinypilot-privileged/init-usb-gadget` to be keyboard only as outlined in  https://github.com/mtlynch/ansible-role-tinypilot/compare/keyboard-only#diff-c8573b91dc16a6cfda03f87344d3cde292fa75544950b155f815eb5693e2467e in case it didn't like the multi-device

I have a straight USB-A to USB-A connector via the USB 2.0 port (also tried the USB 3.0 one)

## What's the behavior that you expect?

When pressing a key, it to show on the screen.

## What's happening instead?

No key passthrough is working.

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Chrome
2. Press a key on keyboard or on screen keyboard
4. Nothing is passed to guest

## Logs

http://sprunge.us/IE0ZbR

**Comment by mtlynch** [comment]
Thanks for reporting this!

>I have a straight USB-A to USB-A connector via the USB 2.0 port (also tried the USB 3.0 one)

TinyPilot requires the connection through the Pi's USB-C port, as it's the only port on the Pi with USB OTG support.

See this post for details: <https://mtlynch.io/tinypilot/#connect-to-the-machine-via-usb>
