### ISSUE TITLE
Documentation Clarifications

### ISSUE THREAD

**Issue by cdgriffith** [mtlynch/tinypilot#603]
1. https://github.com/mtlynch/tinypilot/wiki/Troubleshooting-and-Diagnostics#browser-console-logs  shouldn't suggest to use `F12` to open the console, as that is captured for input

2. https://github.com/mtlynch/tinypilot/wiki/Troubleshooting-and-Diagnostics#browser-console-logs  does not specify where to update the environment variables, should add they are in ` /lib/systemd/system/tinypilot.service` 

3. Not clearly mentioned of where tinypilot is installed by default: `/opt/tinypilot`    - would suggest adding to https://github.com/mtlynch/tinypilot#simple-installation

**Comment by mtlynch** [comment]
Thanks for reporting these!

>https://github.com/mtlynch/tinypilot/wiki/Troubleshooting-and-Diagnostics#browser-console-logs shouldn't suggest to use F12 to open the console, as that is captured for input

Good point, fixed!

>Not clearly mentioned of where tinypilot is installed by default: /opt/tinypilot - would suggest adding to https://github.com/mtlynch/tinypilot#simple-installation

True. Fixed in #608.

>https://github.com/mtlynch/tinypilot/wiki/Troubleshooting-and-Diagnostics#browser-console-logs does not specify where to update the environment variables, should add they are in /lib/systemd/system/tinypilot.service

Is that the correct URL? I don't see the mention of environment variables you're talking about in that section.

**Comment by cdgriffith** [comment]
Whoops second one was a bad double paste. Under the Options on the Readme for environmental vars.
