### ISSUE TITLE
Unstable video

### ISSUE THREAD

**Issue by Kostecki** [mtlynch/tinypilot#613]
## Description

I get frequent flickering between showing the video output and the "no signal" screen. It'll show video, switch to "no signal" for a moment and then back to video. Repeating forever.

Sometimes it'll even throw up in the console and kill video output altogether

## What's the behavior that you expect?

For TinyPilot to show video output from my server. Indefinitely.

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Chrome
2. See error

## Logs
TinyPilot: https://logs.tinypilotkvm.com/gbVG7ayG
Kernel errors: https://pastebin.com/wyCJ2eqd

Sceen recording: https://imgur.com/uW6lpO9

**Comment by mtlynch** [comment]
Thanks for reporting this. What device are you using for video capture?

**Comment by Kostecki** [comment]
The generic ebay/aliexpress small form factor hdmi capture device

**Comment by mtlynch** [comment]
I think this is a failure in your capture device. The USB to HDMI dongles are low-cost, but they're not the most reliable. It seems like about 2-3% of them are defective. Would it be possible for you to try a different dongle? I like [these](https://smile.amazon.com/dp/B08CXWPYQ8/), but they're also available on AliExpress.

Feel free to reopen if you see this reproduce on another dongle.

**Comment by Kostecki** [comment]
I'll grab one of those and give it a try 👍
