### ISSUE TITLE
HDMI output loads after OS starts

### ISSUE THREAD

**Issue by SillySusage** [mtlynch/tinypilot#638]
Hi there :)
Yesterday I installed Tinypilot on a Raspberry Pi 4 and with the recommended USB to HDMI dongle.

I can get screen output from devices and input keystrokes on the machines(so far so good!)

There is one thing that I seem to struggle with:
When I turn on a PC the HDMI output waits until the OS is fully loaded meaning that I can't get into the BIOS.
One of the key features I need for this is being able to enter the BIOS while working remotely.
I have seen some videos with people having no issues entering the BIOS so I believe it should be possible. 
Do I need to do something special for this to work or does it depend on what machines I'm using it on?

Sorry if this is a stupid question, I have tried searching for the solution here but maybe I'm using the wrong keywords for my search.

**EDIT:**
Sorry! I found the solution.
In case anybody else has same issue(Lenovo Thinkpads) do the following:
1. Go to BIOS
2. Go to Config
3. Go to Display
4. Select "Boot Display Device" and change it to "External Display"

**Comment by mtlynch** [comment]
Thanks for reporting this and sharing the solution!

I hadn't run into this with Lenovo laptops, but it'll be good to know for the future.
