### ISSUE TITLE
Set `error` property to `null` in `latest-update-result.json`

### ISSUE THREAD

**Issue by jotaen** [mtlynch/tinypilot#665]
When writing `latest-update-result.json` to disk, we still use empty string for indicating that there is no error. The code in the `app/update` package, however, uses `None` internally and has to convert from empty string to `None` (https://github.com/mtlynch/tinypilot/blob/master/app/update/result.py#L36). In the tests we also consistently use `null` instead of empty string.

I suppose the only change we need is in https://github.com/mtlynch/tinypilot/blob/master/scripts/update-service#L61, but I’m not super familiar with the update code, so maybe you have a better overview.

**Comment by mtlynch** [comment]
Oh, good catch.

The conversion from empty string to None in the reader is intended for legacy files, so we should change the default to None.
