### ISSUE TITLE
Detect device connected

### ISSUE THREAD

**Issue by L-P-G** [mtlynch/tinypilot#684]
Is there a command we can run from the Pi OS to detect if a PC is connected? Trying to find a way to rule out a blank screen being a locked system or just no signal/nothing connected.

**Comment by mtlynch** [comment]
A blank screen means that the system is outputting a blank screen. When TinyPilot doesn't have any signal, it will display "No Signal"

![image](https://user-images.githubusercontent.com/7783288/117988070-126ad180-b309-11eb-8f63-efdc28b3a510.png)
