### ISSUE TITLE
Send CTRL-ALT-Del key sequence needs to be under the Actions menu

### ISSUE THREAD

**Issue by glendady** [mtlynch/tinypilot#696]
To use TinyPilot with Windows Server OS, from NT 3.51 forward requires sending the Ctrl-Alt-Del key sequence to start the logon process.  Many commercial remote console products, like VMware's Remote Console have buttons to send this key sequence, because pressing those keys is handled by the local machine first.  Currently to do this with TinyPilot, you must bring up the virtual keyboard and press the keys individually.  This is a feature that is required is TinyPilot is going to make any in roads to data centers that employ Windows Server machines.

**Comment by mtlynch** [comment]
Thanks! I agree, this is something we need to add.

We're currently tracking this in #481.
