### ISSUE TITLE
No mouse with Avocent DSR 4020 16-port KVM switch

### ISSUE THREAD

**Issue by glendady** [mtlynch/tinypilot#697]
## Description

The mouse cursor does not function when TinyPilot  is connected to a Windows Server trough an Avocent DSR 4020 KVM Switch

## What's the behavior that you expect?

I would expect that the mouse cursor would follow the mouse on the remote machine connecting through the TinyPilot web interface 

## What's happening instead?

No mouse functionality.  Remote mouse cursor is either not present, or does not follow the mouse on the machine connected to the TinyPilot web interface

## What are the steps to reproduce this behavior?

1. TinyPilot is connected to an Avocent DSR 4020 KVM Switch
2. Open TinyPilot in Chrome
2. Press Scroll Lock to bring up OSD.  The mouse cursor is present but does not track with the mouse on my laptop
4. You can use the arrow keys to select a server from the OSD
5. Once connected to the server the mouse cursor is no longer present

## Screenshots

![image](https://user-images.githubusercontent.com/84284244/118568543-0edeac80-b746-11eb-9702-cc60919c3001.png)

![image](https://user-images.githubusercontent.com/84284244/118568650-45b4c280-b746-11eb-89a4-8718473d2344.png)

## Logs

Please paste the URL you see when you run `/opt/tinypilot/dev-scripts/dump-logs`

http://logs.tinypilotkvm.com/ZS9l5osq

**Comment by mtlynch** [comment]
Thanks for reporting this!

Unfortunately, this is likely a limitation of the KVM and not something we can fix from the TinyPilot side. Most KVMs expect a direct connection to a keyboard or mouse, so if you have multiple devices on the same connection, the KVM ignores some or all of them.

You can confirm this if you plug a physical keyboard and mouse into the Avocent via a USB hub. If it doesn't recognize the mouse through a USB hub, it's not possible for TinyPilot to do better.

I'm maintaining a summary of KVM compatibility on the wiki, and I've just added the DSR 4020:

https://github.com/mtlynch/tinypilot/wiki/KVM-compatibility
