### ISSUE TITLE
ARM64 is not supported.

### ISSUE THREAD

**Issue by bgulla** [mtlynch/tinypilot#90]
Thanks for this great project 

When installing on an arm64-based Raspian installation, I received the following error on installation (via `curl`): 

`Command "/tmp/tmp.0izQM6JOtJ/venv/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xlsfga9z --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools>=40.6.0 wheel "cffi>=1.8,!=1.11.3; platform_python_implementation != 'PyPy'"" failed with error code 1 in None`

By disabling `arm64 (arm_64bit=0)`, the installation succeeds as intended.

**Comment by mtlynch** [comment]
Thanks for reporting this! We're currently tracking 64-bit support in #79. I don't have a 64-bit device on hand, but I'll order one this week.
