### ISSUE TITLE
Perform software upgrade through the web interface

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/tinypilot#91]
Currently the user can upgrade to the latest stable version by simply running SSH'ing in and running:

```bash
/opt/tinypilot/scripts/upgrade
```

But it would be better if the user could do this right from the web interface.

### Notes

* We can retrieve the release tag in the installed version from `git tag | tail -n 1`
* We can retrieve the releases from Github using `curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/mtlynch/tinypilot/releases`

#### Ansible

The first thing we need to do is move `scripts/upgrade` to `/opt/tinypilot-privileged/update`.

*(note the change from `update` -> `upgrade`). Now that we have two version, I want to use "update" to refer to version-to-version updates and "upgrade" to refer to free -> Pro upgrade)*

We can follow a similar pattern that we applied in:

https://github.com/mtlynch/ansible-role-tinypilot/pull/68

Except for one difference: the `tinypilot` user should have `sudoers` access to `/opt/tinypilot-privileged/update`. The `tinypilot` user currently has sudoers access to the `/sbin/shutdown` binary, via [this Ansible play](https://github.com/mtlynch/ansible-role-tinypilot/blob/24461e2189e22f35ff6b8e2b18ed04f2f4d9c6d9/tasks/main.yml#L38).

We should keep `scripts/upgrade` instead of deleting it entirely, but change it to just print out an error saying, "This script has moved to /opt/tinypilot-privileged/update" and return -1 in case users have scripts that call this path.

#### Backend

Add three new routes:

* `/api/version` (GET)
  * Return the installed version according to the current git commit ID.
* `/api/latestRelease` (GET)
  * Return the latest version available on the Github repo according to the HEAD commit ID on master in the mtlynch/tinypilot repo.
* `/api/update` (POST)
  * Perform an update by running `/opt/tinypilot-privileged/update` under sudoer context.

#### Frontend

Add a menu item under ~~"Options"~~ "Commands" called "Update". When the user presses this option, a dialog should pop up. In the background, the frontend calls `/api/version` and `/api/latestRelease`.

If `version != latestRelease` the dialog should say, "An update is available. Would you like to install the latest version?" Giving options "Update" or "Cancel." If the user selects "Update," the frontend should call `/api/update`, and if that succeeds, `/api/restart`. During the update, the dialog should show a countdown timer from five minutes and show the message, "Please wait while TinyPilot updates."

If `version == latestRelease`, the dialog should say, "You are running the latest version of TinyPilot" and an "OK" button that closes the dialog.

This UI is overly simple for the first pass, and we can try adding more details later.

**Comment by somik123** [comment]
Maybe you could look into integrating a web-SSH sever on the Pi and make it accessible through the web UI of tinyPilot?

**Comment by mtlynch** [comment]
Fixed in #443
